[versions]
agp = "8.13.0"
androidGpuimage = "v1.4.1-eincs-1.0.1"
androidImageCropper = "4.6.0"
glide = "5.0.5"
gpuimage = "2.1.0"
gpuimageVersion = "2.1.0"
gravitysnaphelper = "2.2.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
koinAndroidxViewmodel = "2.0.0"
lifecycleViewmodelKtx = "2.9.4"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
roundedimageview = "2.3.0"
sdpAndroid = "1.1.1"
sspAndroid = "1.1.1"
ucrop = "2.2.11"
ucropVersion = "2.2.11"

[libraries]
android-gpuimage = { module = "jp.co.cyberagent.android:gpuimage", version.ref = "gpuimageVersion" }
android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
eincs-android-gpuimage = { module = "com.github.eincs:android-gpuimage", version.ref = "androidGpuimage" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gpuimage-v210 = { module = "jp.co.cyberagent.android:gpuimage", version.ref = "gpuimage" }
gravitysnaphelper = { module = "com.github.rubensousa:gravitysnaphelper", version.ref = "gravitysnaphelper" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
koin-androidx-viewmodel = { module = "org.koin:koin-androidx-viewmodel", version.ref = "koinAndroidxViewmodel" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
roundedimageview = { module = "com.makeramen:roundedimageView", version.ref = "roundedimageview" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
ucrop-v229native = { module = "com.github.yalantis:ucrop", version.ref = "ucropVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

